# Generated by Django 4.1.1 on 2023-01-18 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proveedor', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=300)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
