# Generated by Django 4.1.1 on 2023-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categoria/%Y/%m/%d'),
        ),
    ]
