# Generated by Django 4.1.1 on 2023-02-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Propietario')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('comentario', models.CharField(max_length=150, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Empresa')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d')),
            ],
        ),
    ]
