# Generated by Django 4.1.1 on 2023-01-18 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSalidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(default=datetime.datetime.now)),
                ('cod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida_stock', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_salida', models.DateField(default=datetime.datetime.now)),
                ('cod_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_compras.facturasalidas')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(default=datetime.datetime.now)),
                ('cod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingreso_stock', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('cod_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_compras.facturaentrada')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
